

services:

  soccerhub-api:
    build: .
    container_name: soccerhub-api

    ports:
      - "8080:8080"

    depends_on:
      - sqlserver

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=SoccerHubDb;User Id=sa;Password=SoccerHub2026!;TrustServerCertificate=True"

  sqlserver:

    image: mcr.microsoft.com/mssql/server:2022-latest

    container_name: soccerhub-db

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SoccerHub2026!"

    ports:
      - "1433:1433"

    volumes:
      - sql_data:/var/opt/mssql

volumes:

  sql_data: